### ISSUE TITLE
wakayama.rbボードへの対応

### ISSUE THREAD

**Issue by sean2121** [kimushu/rubic#1]
wakayama.rbボードへの対応を予定されているとのことですが、いつ頃を予定されてますか？
wakayama.rbボードを使った教育向けプロジェクトでぜひ、rubicをIDEとして使えたらいいなぁーと思いました。

**Comment by kimushu** [comment]
ありがとうございます。現状は9月に山口で開催されるイベント(YMMF)に間に合えばいいな、というペースです。
ただ、手元ではすでに動く物がありまして(for ARIDA V2.0以降)、ボード選択部の大改造と合わせて公開しようとしているので遅延しています。要望があれば数段階に分けて出せるかもしれません。

**Comment by kimushu** [comment]
すみません、だいぶ前のissueですが、現バージョンですでにWakayama.rb対応しておりますので、クローズさせていただきます。
