### ISSUE TITLE
実行時に転送に失敗することがある。

### ISSUE THREAD

**Issue by takjn** [kimushu/rubic#5]
Rubic 0.9.0、ボード種別はCITRUS、ファームウェアのリビジョンは2.13(2016/10/1)で、実行時の転送に失敗することがあります。

> ビルドに成功しました
> main.mrb を転送しています...失敗しました

main.mrbのファイルサイズ は -g オプションを外した状態で9023 バイトです。同じファイルでRubic 0.2.4のときは、CITRUSからのエラーメッセージ（size is greater than 8192）が表示されました。
Rubic 0.9.0では、TimeoutErrorとなってしまうようです。

Chromeのログは以下の通りです。

```
window.js:1 Popup {message: "Failed to transfer 1", title: "Transfer failed"}module.exports.App._popupMessage @ window.js:1(anonymous function) @ window.js:5(anonymous function) @ window.js:8
window.js:3 Uncaught (in promise) TimeoutError {message: "timeout error", name: "TimeoutError"}

```

タイムアウトの時間を長くすることはできますでしょうか？

**Comment by kimushu** [comment]
CITRUS側ファームの仕様で一つのmrbファイルは8192バイトまでとなっています。
よって、タイムアウト時間を伸ばしても解決しません。今のところ、mrbを別ファイルに分けるしかありません。

なお、エラーメッセージ(size is greater than 8192)が表示されないのは0.9.0の不具合ですね。。

**Comment by kimushu** [comment]
なお、タイムアウト値をユーザ側では変更できません。
ただし、書き込み等の時間がかかる操作に対しては、その転送サイズに応じたタイムアウト値が設定されます。
GR-CITRUSおよびWakayama.rbでの書き込みは「2秒/kB」です。

**Comment by takjn** [comment]
了解です、ありがとうございます！

**Comment by kimushu** [comment]
こちらこそ、早速のレポートありがとうございます。
ひとりでやっていると気付かないところも多々あるので、ご報告いただけると助かります。
